# Generated by Django 3.2.9 on 2022-01-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('view', models.CharField(max_length=20)),
                ('detachment', models.CharField(max_length=20)),
                ('suborder', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('genus', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
