# Generated by Django 3.2.9 on 2022-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dino_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dino',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
